export const SET_APPLICATION_DATA = "SET_APPLICATION_DATA";
export const PAGE_ROUTER_DATA = "PAGE_ROUTER_DATA";

export const PRODUCT_DIALOG_DATA = "PRODUCT_DIALOG_DATA";

export const ENVIRONMENT = "ENVIRONMENT";

export const FIREBASE_DEVICE_KEY = "FIREBASE_DEVICE_KEY";
