import { StyleSheet } from "react-native";
import {normalize} from "@/shared/helpers";
import {labels, palette} from "@/shared/constants/colors.ts";

export const styles = StyleSheet.create({
    container: {
        flex : 1,
        width: "100%",
        flexDirection: "column",
        display: "flex",
        paddingHorizontal: normalize(10),
        height: '100%',
    },
    medName: {
        fontSize: normalize(15),
        fontWeight: "600",
        color: "#333",
        marginBottom: 4,
    },
    medInfo: {
        flex: 1,
        justifyContent: "space-between",
    },
    addMedicationButtonText: {
        color: "white",
        fontWeight: "600",
    },
    addMedicationButton: {
        backgroundColor: "#1a8e2d",
        paddingHorizontal: normalize(20),
        paddingVertical: normalize(10),
        borderRadius: normalize(20),
        marginTop: normalize(10),
    },
    reminderInfoPrimary: {
        fontSize: normalize(14),
        color: labels.type4.textColor,
        backgroundColor: labels.type4.background,
        marginBottom: normalize(4),
        padding: normalize(2),
        paddingLeft : normalize(10),
        paddingRight : normalize(10),
        borderRadius: normalize(10),
    },
    reminderInfoSuccess: {
        fontSize: normalize(14),
        color: labels.type3.textColor,
        backgroundColor: labels.type3.background,
        marginBottom: normalize(4),
        padding: normalize(2),
        paddingLeft : normalize(10),
        paddingRight : normalize(10),
        borderRadius: normalize(5),
    },
    reminderInfoBlue: {
        fontSize: normalize(14),
        color: labels.type3.textColor,
        backgroundColor: labels.type3.background,
        marginBottom: normalize(4),
        paddingHorizontal: normalize(1),
        padding: normalize(2),
        paddingLeft : normalize(10),
        paddingRight : normalize(10),
        borderRadius: normalize(5),
    },
    medBadge: {
        width:  normalize(50),
        height: normalize(50),
        borderRadius: normalize(25),
        justifyContent: "center",
        alignItems: "center",
        marginRight: normalize(15),
    },
    medCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "white",
        borderRadius: normalize(10),
        padding: normalize(16),
        marginBottom: normalize(12),
        shadowColor: "#000",
        shadowOffset: { width: 0, height: normalize(2) },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
    },
    medTime: {
        flexDirection: "row",
        alignItems: "center",
    },
    dateCreated: {
        marginLeft: 5,
        color: "#666",
        fontSize: 14,
    },
    headerContent: {
        flexDirection: 'row',
        paddingBottom: normalize(10),
        paddingHorizontal : normalize(15),
        marginTop : normalize(10)
    },
    headerTop: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 20,
    },
    title: {
        fontSize: normalize(15),
        fontWeight: '700',
        color : 'white',
        width : '90%',
        textAlign : 'center',
        justifyContent : "center",
    },
});
